#!/bin/bash
declare -A w=(["w"]=0 ["a"]=1 ["t"]=2 ["e"]=3 ["r"]=4) s=(["s"]=0 ["t"]=1 ["i"]=2 ["r"]=3) b=(b e s t c h o l) d=0 o=; for((i=0;i<${#WATER};i++)); do d=$((d*5 + w[${WATER:i:1}])); done; for((i=0;i<${#STIR};i++)); do d=$((d + s[${STIR:i:1}]*4**(${#STIR}-1-i))); done; while((d>0)); do o=${b[d%8]}$o; d=$((d/8)); done; echo ${o:-b}
